### ISSUE TITLE
Dateirechte (ausführbar)

### ISSUE THREAD

**Issue by gharlan** [FriendsOfREDAXO/demo_onepage#10]
Die Dateien haben alle das Ausführungsrecht. Das sollten sie aber nicht haben.
Zu sehen, wenn man eine Datei öffnet, links oben ("Executable File"). Beispiel:
https://github.com/FriendsOfREDAXO/demo_onepage/blob/master/boot.php

**Comment by polarpixel** [comment]
Oh, das kommt von meiner lokalen Installation.
@gharlan Hast Du hei erine Empfehlung, welche Rechte die Dateien (php, yml, css, lang, md) jeweils haben sollten?

**Comment by gharlan** [comment]
Ich hab nochmal nachgelesen, wie git mit Dateirechten umgeht. Wenn ich es richtig verstehe, ist für git nur relevant ob die Datei Ausführungsrechte für den aktuellen User hat, oder nicht.
Oder mit anderen Worten, für git ist nur relevant, ob es 6xx oder 7xx ist.
Und Ausführungsrecht (7xx) sollten nur Dateien haben, die man direkt als Script in der Console aufrufen können soll (wie zum Beispiel `redaxo/bin/console`).

Solche Dateien hast du hier im Repo aber nicht, es sollten also alle Dateien 6xx sein. Ob du daraus bei dir lokal dann nun 666, 664, 644 oder so machst, ist aus git-sicht egal, nur vorne sollte keine 7 stehen.

@staabm gerne korrigieren, falls ich Mist erzähle.

**Comment by staabm** [comment]
Kann ich nix zu sagen (ausser das das Executable bit nicht vorhanden sein sollte bei den meisten Dateien, wie richtig angemerkt)

**Comment by polarpixel** [comment]
Ist korrigiert, danke für den Hinweis.
