### ISSUE TITLE
Wie inschdalliert ma des eigendlich?

### ISSUE THREAD

**Issue by simonsinus** [FriendsOfREDAXO/demo_onepage#17]
kT

**Comment by schuer** [comment]
Im REDAXO-Adminbereich links in der Sidebar auf »Installer« klicken. Dann in der Tableiste auf »Neue AddOns installieren« (oder so ähnlich, hab’s gerade nicht vor mir). Die Suche benutzen, um `demo_onepage` zu finden. Draufklicken, installieren.  

Danach in der Sidebar auf AddOns klicken und in der Liste der vorhandenen AddOns die neu hinzugekommene Onepage-Demo aktivieren.  

Abschließend in der Sidebar auf den neu hinzugekommenen Menüpunkt Onepage-Demo klicken und dort den Button zum Installieren anklicken. Das war’s.

**Comment by schuer** [comment]
Alternativ kannst du AddOns manuell runterladen, etwa von GitHub, und sie im AddOns-Ordner deiner REDAXO-Installation ablegen. Dabei drauf achten, dass der Ordner so heißt wie das AddOn, in diesem Fall also `demo_onepage`.

Danach taucht es im REDAXO-Adminbereich auf und du kannst es aktivieren und danach die Demo installieren wie oben beschrieben.
