### ISSUE TITLE
Templates nicht zugewiesen

### ISSUE THREAD

**Issue by darwin26** [FriendsOfREDAXO/demo_onepage#2]
Hi,
in der Demo / Installation - sind nach der Installation bei den Kategorien:
**/Start/** und **/Abschnitte als Module/** "nur" das DEFAULT eingebunden.
Das wirft beim Aufrufen der Seite leider gleich einen Fehler im Modul(id:1 / Zeile 15) bzw. wird in dem Default-Template der Header nicht eingebunden... Könnt etwas für Verwirrung sorgen, wenn man beim Aufruf einen OOOPS erhält...

**Comment by polarpixel** [comment]
Dieses Problem haben komischerweise nur einige wenige, und ich versteh nicht, wieso.
Eigentlich müsste doch die template-Tabelle bei der Installation gelöscht werden, oder?
https://github.com/FriendsOfREDAXO/demo_onepage/blob/master/backups/demo_onepage.sql#L597

**Comment by Himra** [comment]
Hi,
hab das selbe Problem wie kann ich es beheben?

**Comment by christophboecker** [comment]
ist wirklich seltsam und schwer nachvollziehbar. Ich hatte das Problem auch. Leeres, aktuelles Redaxo, Demo installiert. Woops verweist auf Modul 1, Zeile 15. `getProperty('anchors')` findet nichts. Mehrfach die Demo neu installiert, Cache gelöscht; stets das selbe Ergebnis. Manuell im Adminer alle Tabellen truncated bzw. von der Demo hinzugefügte Teile inkl. der Addons händisch entfernt, Demo neu installiert. Läuft. Rätselhaft.

**Comment by staabm** [comment]
irgendwelche fehler im syslog die ggf. hinweise liefern?

**Comment by christophboecker** [comment]
Da hatte sich nur der Whoops verewigt, der besagt, dass der Befehl `rex::getProperty('anchors')->append($items);` aus Modul1/Output/Zeile15 nicht ausgeführt werden kann. Testausgabe zeigte, dass  `rex::getProperty('anchors')` null zurückliefert.

**Comment by staabm** [comment]
Wo sieht man den fehler? Backend/Frontend?

Wo wird das propery gesetzt damit es dort zur Verfügung stehen kann?

**Comment by staabm** [comment]
Wo sieht man den fehler? Backend/Frontend?

Wo wird das propery gesetzt damit es dort zur Verfügung stehen kann?

**Comment by christophboecker** [comment]
Der Fehler erscheint beim Anzeigen der Frontend-Startseite.  Zwei zufällig ausgewählte Unterseiten aus dem Backend per Vorschau-Button gestartet, erzeugten keinen Whoops. Startseite per Vorschau-Button lieferte den Whoops. Mehr kann ich nicht beitragen.

**Comment by polarpixel** [comment]
Das Problem entsteht, wenn das Standard-Template nicht gelöscht wird, sondern weitere Templates angehängt werden und dann die Referenzierung nicht mehr stimmt. Wir können es aber nicht reproduzieren, und es tritt auch nur bei einigen Usern auf. Bei mir auch nur einmal, danach nicht mehr. Und wir verstehen auch nicht, warum es auftritt.
Eine Neuinstallation der Demo behebt dann eigentlich das Problem. Deshalb schließe ich hier erstmal.
