### ISSUE TITLE
background-image jitter beim scrollen auf iOS chrome

### ISSUE THREAD

**Issue by cukabeka** [FriendsOfREDAXO/demo_onepage#20]
Wegen der 80vh Definition für das background-image ruckeln die header- und hintergrundbilder auf iOS in Chrome.

Lösung, siehe https://stackoverflow.com/questions/24944925/background-image-jumps-when-address-bar-hides-ios-android-mobile-chrome

```
.section .responsive-background, .section .full-image {
    transition: height 1000000s ease;
    -webkit-transition: height 1000000s ease;
    -moz-transition: height 1000000s ease;
    -o-transition: height 1000000s ease;
}
```

**Comment by polarpixel** [comment]
Habe ich hinzugefügt, danke.
