### ISSUE TITLE
Template ID=1 ("Default") ist leer in der aktuellen Version

### ISSUE THREAD

**Issue by interweave-media** [FriendsOfREDAXO/demo_onepage#24]
In der aktuellsten Variante ist das vorher als "01 . Abschnitte als Module" benannte Template ID1 jetzt in "Default" umgetauft worden, hat aber nicht den Code mitbekommen, es ist also inhaltsleer!

**Comment by polarpixel** [comment]
Das Problem entsteht, wenn das Standard-Template nicht gelöscht wird, sondern weitere Templates angehängt werden und dann die Referenzierung nicht mehr stimmt. Wir können es aber nicht reproduzieren, und es tritt auch nur bei einigen Usern auf. Bei mir auch nur einmal, danach nicht mehr. Und wir verstehen auch nicht, warum es auftritt.
Eine Neuinstallation der Demo behebt dann eigentlich das Problem. Deshalb schließe ich hier erstmal.

**Comment by interweave-media** [comment]
Das Standard-Template lässt sich ja nicht löschen ?! Anyway: ich habe das Problem nach wie vor und jedesmal mit der neuesten Variante der Onepage-Demo. Eine Neuinstallation der Demo hilft nicht wirklich. Es taucht nur mit der aktuellen Version der Demo auf, die erste Version hatte das Problem nicht (dort hatte das Standard-Template auch einen eigenen, anderen Namen..)

**Comment by polarpixel** [comment]
Kannst Du mir genau beschreiben, wie Du vorgehst, damit ich das ggf. nachvollziehen kann? Wir hatten gemeinsam drüber gekuckt und verstehen nicht, warum das passiert.
In der Installation wird eigentlich hier die Template-Tabelle gelöscht, falls eine vorhanden ist:
https://github.com/FriendsOfREDAXO/demo_onepage/blob/master/backups/demo_onepage.sql#L599
Und dann eben neu angelegt mit meinen Tabellen.
Mit meinem Kommentar oben meinte ich also eine automatische Löschung.

**Comment by interweave-media** [comment]
Das ist ganz einfach: 
- Frische Installation des aktuellen redaxo-CMS (5.6.4) auf einen neuen Serverplatz
- Installation des Onepage-Addon
- Aktivierung des Addons
default-Template ist leer.
Ist jetzt schon auf drei verschieden Serverplätzen genauso abgelaufen.
In der ersten Version des Addons tauchte das Problem nicht auf, dort waren dann nur die vom Addon gestellten Templates installiert. Das Template ID=1 hatte dabei auch einen eigenen Namen und nicht "default".
