### ISSUE TITLE
rex_exception Fragmentfile "introblock.php" not found!

### ISSUE THREAD

**Issue by ansichtsache** [FriendsOfREDAXO/demo_onepage#27]
Wird das Addon deaktiviert – was ja nach der Installation möglich sein sollte – wirft das Modul "01 . Header" im Backend wenn man bearbeiten will einen Fehler: `rex_exception
Fragmentfile "introblock.php" not found!` Wird das Addon wieder aktiviert, läßt sich auch der Block mit dem Modul wieder bearbeiten.
![bildschirmfoto 2018-11-13 um 16 17 16](https://user-images.githubusercontent.com/4320057/48422809-b5096000-e75f-11e8-8d55-3deceeaf51f1.jpg)

**Comment by polarpixel** [comment]
> Wird das Addon deaktiviert – was ja nach der Installation möglich sein sollte

Da hast Du im Prinzip recht. aber ich wollte halt einige eigene, Website-spezifische Features hinzufügen (eigenes CSS und JS im Backend, eigenes Fragment) und habe überlegt, wie man es update-sicher integriert. Man könnte es in das Projekt-AddOn packen, in das Theme-AddOn oder eben in das Demo-eigene AddOn. Letzteres schien mir am besten, da man das ja ohnehin installiert und ich die Abhängigkeiten zu anderen AddOns so gering wie möglich halten wollte.
Ich würde daher jetzt nicht die Funktionen in das Projekt-AddOn überführen und dies als Voraussetzung definieren, sondern lediglich im Text irgendwo ergänzen, dass das Demo-AddOn nicht deaktiviert werden sollte und warum nicht.

**Comment by staabm** [comment]
ggf. solltest du an der stelle abfragen, ob das addon installiert ist:

```php
if (!rex_addon::get('dein addon')->isAvailable()) {
  echo "dieses modul benötigt das addon 'dein addon'";
  return;
}
```

damit vermeidest du dann den error und führst den user zudem

**Comment by polarpixel** [comment]
Gute Idee, danke!

**Comment by polarpixel** [comment]
Danke für die Hilfe!
Sollte mit 1.2.3 behoben sein.
