### ISSUE TITLE
Call to a member function append() on null

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/demo_onepage#28]
demo installiert, danach direkt das frontend aufgemacht:

![image](https://user-images.githubusercontent.com/120441/50383140-31238b80-06ae-11e9-95bd-da51ad99dac1.png)

**Error:** Call to a member function append() on null
**File:** rex:\\module\output
**Line:** 15

<details>
<summary>Stacktrace</summary>

| Function                                     | File                                                                     | Line     |
| -------------------------------------------- | ------------------------------------------------------------------------ | -------- |
| require                                      | redaxo\cache\addons\structure.1.content                                | 90       |
| require                                      | redaxo\src\addons\structure\plugins\content\lib\article_content.php      | 102      |
| rex_article_content->getArticle              | rex:\\template                                                        | 1        |
| require                                      | redaxo\src\addons\structure\plugins\content\lib\article_content_base.php | 416      |
| rex_article_content_base->getArticleTemplate | redaxo\src\addons\structure\plugins\content\boot.php                     | 80       |
| rex_package->{closure}                       | redaxo\src\core\lib\extension.php                                        | 45       |
| rex_extension::registerPoint                 | redaxo\src\core\frontend.php                                             | 22       |
| require                                      | redaxo\src\core\boot.php                                                 | 152      |
| require                                      | index.php                                                                | 9        |

</details>
<details>
<summary>System report (REDAXO 5.7.0-beta1#eb3b29c39, PHP 7.3.0)</summary>

| REDAXO        |                       |
| ------------: | :-------------------- |
|       Version | 5.7.0-beta1#eb3b29c39 |

| PHP           |            |
| ------------: | :--------- |
|       Version | 7.3.0      |
|       OPcache | no         |
|        Xdebug | no         |

| Database      |                        |
| ------------: | :--------------------- |
|       Version | 5.5.5-10.1.37-MariaDB  |
| Character set | utf8 (utf8_general_ci) |

| Server        |                |
| ------------: | :------------- |
|            OS | WINNT          |
|          SAPI | apache2handler |
|     Webserver | Apache/2.4.37  |

| Request       |              |
| ------------: | :----------- |
|       Browser | Firefox/66.0 |
|      Protocol | HTTP/1.1     |
|         HTTPS | no           |

| Packages            |             |
| ------------------: | :---------- |
|              backup | 2.3.0-beta1 |
|            be_style | 2.7.0-beta1 |
| be_style/customizer | 2.7.0-beta1 |
|     be_style/redaxo | 2.7.0-beta1 |
|        demo_onepage | 1.2.2       |
|           developer | 3.7.0       |
|             install | 2.4.1-beta1 |
|            markitup | 3.2.0       |
|              mblock | 3.0.1       |
|       media_manager | 2.6.0-beta1 |
|           mediapool | 2.5.0-beta1 |
|            metainfo | 2.3.2-beta1 |
|             project | dev         |
|           structure | 2.7.0-beta1 |
|   structure/content | 2.7.0-beta1 |
|               users | 2.5.2-beta1 |

</details>

**Comment by staabm** [comment]
fix fürs problem:

Modul: 00 . Navigationspunkt (Anker) - output

statt
		`rex::getProperty('anchors')->append($items);`
nimmt man
		`rex::getProperty('anchors', new ArrayIterator())->append($items);`

damit kommt es nicht zum error, wenn man das Modul `00 . Navigationspunkt (Anker) - output` nicht in verbindnung mit `Multipage.template` verwendet

**Comment by polarpixel** [comment]
Vielen Dank für die Hilfe!
Sollte mit 1.2.3 behoben sein.
