### ISSUE TITLE
Call to a member function getArticles() on null

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/demo_onepage#29]
![screenshot 2019-01-05 at 22 14 16 1](https://user-images.githubusercontent.com/1297466/50729277-69f44380-1137-11e9-91f6-bb69b06a149c.png)

**Error:** Call to a member function getArticles() on null
**File:** rex:///template/2
**Line:** 42

<details>
<summary>Stacktrace</summary>

| Function                                     | File                                                                     | Line     |
| -------------------------------------------- | ------------------------------------------------------------------------ | -------- |
| require                                      | redaxo/src/addons/structure/plugins/content/lib/article_content_base.php | 416      |
| rex_article_content_base->getArticleTemplate | redaxo/src/addons/structure/plugins/content/boot.php                     | 80       |
| rex_package->{closure}                       | redaxo/src/core/lib/extension.php                                        | 45       |
| rex_extension::registerPoint                 | redaxo/src/core/frontend.php                                             | 22       |
| require                                      | redaxo/src/core/boot.php                                                 | 152      |
| require                                      | index.php                                                                | 9        |

</details>
<details>
<summary>System report (REDAXO 5.7.0-beta1, PHP 7.2.10)</summary>

| REDAXO        |             |
| ------------: | :---------- |
|       Version | 5.7.0-beta1 |

| PHP           |            |
| ------------: | :--------- |
|       Version | 7.2.10     |
|       OPcache | no         |
|        Xdebug | no         |

| Database      |                        |
| ------------: | :--------------------- |
|       Version | 5.7.23                 |
| Character set | utf8 (utf8_general_ci) |

| Server        |                |
| ------------: | :------------- |
|            OS | Darwin         |
|          SAPI | apache2handler |
|     Webserver | Apache/2.2.34  |

| Request       |                     |
| ------------: | :------------------ |
|       Browser | Chrome/71.0.3578.98 |
|      Protocol | HTTP/1.1            |
|         HTTPS | no                  |

| Packages            |             |
| ------------------: | :---------- |
|              backup | 2.3.0-beta1 |
|            be_style | 2.7.0-beta1 |
| be_style/customizer | 2.7.0-beta1 |
|     be_style/redaxo | 2.7.0-beta1 |
|        demo_onepage | 1.2.2       |
|           developer | 3.7.0       |
|             install | 2.4.1-beta1 |
|            markitup | 3.2.0       |
|              mblock | 2.2.3       |
|       media_manager | 2.6.0-beta1 |
|           mediapool | 2.5.0-beta1 |
|            metainfo | 2.3.2-beta1 |
|             project | dev         |
|           structure | 2.7.0-beta1 |
|   structure/content | 2.7.0-beta1 |
|               users | 2.5.2-beta1 |

</details>

**Comment by schuer** [comment]
Vermutlich sollte $cat geprüft werden, bevor die Artikel ausgelesen werden, etwa so:

```php
$cat = rex_category::get($this->article_id);
if ($cat !== null) {
    // Alle Artikel der aktuellen Kategorie ermitteln mit dem Status online
    $articles = $cat->getArticles(true);
    …
}
```

**Comment by schuer** [comment]
Der Fehler fliegt übrigens nur in REX 5.7, zuvor in REX 5.6 kam er nicht. ¯\\\_(ツ)_/¯

**Comment by staabm** [comment]
> Der Fehler fliegt übrigens nur in REX 5.7, zuvor in REX 5.6 kam er nicht. ¯\_(ツ)_/¯

@schuer Hmm hast du vllt in der config.yml ein always-throw-exception aktiviert, sodass aus einer warning eine exception wird?

**Comment by schuer** [comment]
@staabm Oh, ich habe den Debug-Modus an, sehe ich gerade. :) Daran wird es wohl liegen? Dennoch sollte man das Ergebnis solcher get-Methoden immer prüfen, bevor man damit weiter arbeitet, oder?

**Comment by schuer** [comment]
Update: Fliegt auch mit deaktiviertem Debug-Modus. Und `throw_always_exception: false`.

**Comment by staabm** [comment]
@gharlan @bloep hat jemand eine idee warum dieses error in 5.7 auftaucht, in 5.6 aber nicht?

**Comment by gharlan** [comment]
Ich setze alles auf https://github.com/redaxo/redaxo/issues/2300 :)

**Comment by polarpixel** [comment]
Sollte mit 1.2.3 behoben sein.
