### ISSUE TITLE
Ergebnis-Vorschau der Demo (online)

### ISSUE THREAD

**Issue by madiko** [FriendsOfREDAXO/demo_onepage#3]
Hallo,

zunächst Chapeau für die Arbeit!

Die Screenshots sind sehr vielversprechend und ich sehe deutlich die "Handschrift" von Peter @polarpixel :-)

Vorschlag: Einen Onepager als Sub-Domain zu redaxo.org (http://onepager.redaxo.org) veröffentlichen. Das macht es noch einmal einfacher, sich dafür zu entscheiden (oder eben auch dagegen).

Viele Grüße,
Franziska

**Comment by polarpixel** [comment]
Danke.
Wurde schon häufig angedacht – letztlich muss das @dergel entscheiden.

**Comment by polarpixel** [comment]
Ist derzeit nicht geplant, sorry, deshalb schließe ich hier.
