### ISSUE TITLE
Call to a member function getChildren() on null

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/demo_onepage#30]
![screenshot 2019-01-05 at 22 19 35](https://user-images.githubusercontent.com/1297466/50729317-074f7780-1138-11e9-99fe-2754daaab8fc.png)

**Error:** Call to a member function getChildren() on null
**File:** rex:///template/8
**Line:** 41

<details>
<summary>Stacktrace</summary>

| Function                                     | File                                                                     | Line     |
| -------------------------------------------- | ------------------------------------------------------------------------ | -------- |
| require                                      | redaxo/src/addons/structure/plugins/content/lib/article_content_base.php | 416      |
| rex_article_content_base->getArticleTemplate | redaxo/src/addons/structure/plugins/content/boot.php                     | 80       |
| rex_package->{closure}                       | redaxo/src/core/lib/extension.php                                        | 45       |
| rex_extension::registerPoint                 | redaxo/src/core/frontend.php                                             | 22       |
| require                                      | redaxo/src/core/boot.php                                                 | 152      |
| require                                      | index.php                                                                | 9        |

</details>
<details>
<summary>System report (REDAXO 5.7.0-beta1, PHP 7.2.10)</summary>

| REDAXO        |             |
| ------------: | :---------- |
|       Version | 5.7.0-beta1 |

| PHP           |            |
| ------------: | :--------- |
|       Version | 7.2.10     |
|       OPcache | no         |
|        Xdebug | no         |

| Database      |                        |
| ------------: | :--------------------- |
|       Version | 5.7.23                 |
| Character set | utf8 (utf8_general_ci) |

| Server        |                |
| ------------: | :------------- |
|            OS | Darwin         |
|          SAPI | apache2handler |
|     Webserver | Apache/2.2.34  |

| Request       |                     |
| ------------: | :------------------ |
|       Browser | Chrome/71.0.3578.98 |
|      Protocol | HTTP/1.1            |
|         HTTPS | no                  |

| Packages            |             |
| ------------------: | :---------- |
|              backup | 2.3.0-beta1 |
|            be_style | 2.7.0-beta1 |
| be_style/customizer | 2.7.0-beta1 |
|     be_style/redaxo | 2.7.0-beta1 |
|        demo_onepage | 1.2.2       |
|           developer | 3.7.0       |
|             install | 2.4.1-beta1 |
|            markitup | 3.2.0       |
|              mblock | 2.2.3       |
|       media_manager | 2.6.0-beta1 |
|           mediapool | 2.5.0-beta1 |
|            metainfo | 2.3.2-beta1 |
|             project | dev         |
|           structure | 2.7.0-beta1 |
|   structure/content | 2.7.0-beta1 |
|               users | 2.5.2-beta1 |

</details>

**Comment by schuer** [comment]
Siehe auch #29. Möglicher Bugfix auch hier:

```php
$cats = rex_category::get($this->article_id);
if ($cats !== null) {
    $children = $cats->getChildren(true);
    …
}
```

**Comment by polarpixel** [comment]
Sollte mit 1.2.3 behoben sein.

**Comment by erraiva** [comment]
In der Rex Doku steht 
```
$thisCat = rex_category::get($this->getValue('article_id'));
$children = $thisCat->getChildren();
```
Das führ bei mir noch immer zu 
Error: Call to a member function getChildren() on null

Während das hier funktioniert:
```
$cat = rex_category::getCurrent();
$children = $cat->getChildren(true);
```
Könnt ihr das bestätigen?

**Comment by polarpixel** [comment]
Die erste Option funktioniert bei mir schon noch.
Kann ich also nicht bestätigen.
@erraiva  Taucht es bei Dir in der Demo auf?

**Comment by erraiva** [comment]
Hallo Peter,
ich habe das auch in einer einfachen und runtergedampften Redaxo-Installation. 
Und in der Rex Standard-Demo. Du kannst ausprobieren, ich habe dir ein Admin-Login gemacht:

https://demo.kippnetz.de/redaxo

Login ist 
demo / demo21admin


Wenn du unter der Kategorie "AddOns" den Testartikel aufrufst kommt der Fehler.

Das Template 11 birgt den Subnavi-Code aus der Doku:

-------------------
<?php

$thisCat = rex_category::get($this->getValue('article_id'));
$children = $thisCat->getChildren();
echo '<ul>';
if (is_array($children)) {
 foreach ($children as $child) {
    // Nur wenn Kategorie online
    if ($child->isOnline()) {
    echo '<li><a href="'.rex_getUrl($child->getId()).'">'.$child->getName().'</a></li>';
    }
 }
}
echo '</ul>';

?>
-------------------

Melde dich, wenn du das Login nicht mehr benötigst.

LG Heinz

**Comment by polarpixel** [comment]
Danke für den Link.
Ok, der Fehler entsteht hier, wie Dein Testartikel keine Unterkategorien hat.
Wie schuer weiter oben schrieb, löst man das am besten mit der Prüfung
`if ($cats !== null)`

Ich hab es Dir in der demo eingesetzt.

**Comment by erraiva** [comment]
Danke, dann habe ich das jetzt im Kopf :-)
Ich finde aber das gehört mit in die Doku.
Viele Grüße
Heinz

Von meinem iPad gesendet

**Comment by polarpixel** [comment]
Ja, erst seit Redaxo 5.7 führt dies zu einem Fehler, deswegen ist es wohl noch nicht in der Doku.
Da Redaxo ja ein Community-Projekt ist, ist die Doku eigentlich unsere gemeinsame Aufgabe.
Die gesamte Doku ist in Markdown-Dateien organisiert, jeder kann Änderungen einfügen, und zwar hier:
https://github.com/redaxo/docs
Das Doku-Team übernimmt die Änderungen dann in regelmäßigen Abständen.

**Comment by staabm** [comment]
vllt ist das auch ein bug.. sollten wir untersuchen.

@polarpixel kannst du nen bug mit repro im redaxo repo posten?

**Comment by polarpixel** [comment]
@staabm Ich habe mich falsch ausgedrückt.
Folgender Code
```
$cats = rex_category::get($this->article_id);
$children = $cats->getChildren(true);

```
führt nicht zu einem Fehler, wenn eine Kategorie keine Unterkategorien hat, sondern wenn dieser Code sich auf einem Artikel (also keiner Kategorie) befindet.
Soll ich das dann trotzdem als Issue bei Redaxo schreiben?

**Comment by staabm** [comment]
ich kanns noch nicht 100% umreißen aber nen issue aufmachen und mit den anderen diskutieren sollten wir

**Comment by erraiva** [comment]
Ich habe eine Zeit lang die 404-Seiten oder irdendwelche Hilfs- oder Todo-Seiten, die ich in der Entwicklungsphase brauchte (auch z.B. Footer-Artikel) auf der obersten Strukturebene angelegt, weil sie für mich nicht zum "eigentlichen" Inhalt zählten, der dem Kunden geläufig ist.
Das führte immer wieder zu Fehlern, weil eben die Rootebene keine übergeordnete Kategorie hat. Bei Artikeln scheint das dann ein Problem zu sein. Wäre schön, wenn der Fehler abgefangen würde.
Viele Grüße 
Heinz

**Comment by polarpixel** [comment]
@erraiva 
Siehe hier:
https://github.com/redaxo/redaxo/issues/4571

**Comment by erraiva** [comment]
danke :-)
