### ISSUE TITLE
default template probleme

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/demo_onepage#33]
habe die demo heute in redaxo 5.11 installiert.

im anschluß gibt es anscheinend probleme mit dem neuen default template.

direkt nach dem setup ist das default template ziemlich leer

![grafik](https://user-images.githubusercontent.com/120441/95597269-b1b3a780-0a4e-11eb-8e75-9c0b436fe5e8.png)

und deshalb sieht dann das frontend bescheiden aus weil js und css fehlt

<details>
<summary>System report (REDAXO 5.12.0-dev, PHP 7.4.3, MySQL 8.0.21)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.12.0-dev |

| PHP           |            |
| ------------: | :--------- |
|       Version | 7.4.3      |
|       OPcache | yes        |
|        Xdebug | yes        |

| Database      |              |
| ------------: | :----------- |
|       Version | MySQL 8.0.21 |
| Character set | utf8         |

| Server        |            |
| ------------: | :--------- |
|            OS | Linux      |
|          SAPI | fpm-fcgi   |
|     Webserver | Apache     |

| Request       |              |
| ------------: | :----------- |
|       Browser | Firefox/83.0 |
|      Protocol | HTTP/2.0     |
|         HTTPS | yes          |

| Packages            |            |
| ------------------: | :--------- |
|              backup | 2.6.1      |
|            be_style | 2.11.0     |
| be_style/customizer | 2.11.0     |
|     be_style/redaxo | 2.11.0     |
|        demo_onepage | 1.4.0      |
|           developer | 3.8.0      |
|             install | 2.9.0-dev  |
|            markitup | 3.3.4      |
|              mblock | 3.1.0      |
|       media_manager | 2.10.0     |
|           mediapool | 2.9.0      |
|            metainfo | 2.7.2      |
|             project | dev        |
|           structure | 2.11.1-dev |
|   structure/content | 2.11.1-dev |
|               users | 2.8.0-dev  |

</details>

**Comment by staabm** [comment]
interessant.. selbst wenn ich die tabelle komplett leere und manuell via phpmyadmin neu mit daten bestücke, wird beim 1. request im redaxo backend das template1 wieder überschrieben mit dem inhalt `REX_ARTICLE[]`

**Comment by staabm** [comment]
Kurzum: ich vermute die demo hat probleme damit wenn bereits irgendwelche trmplates angelegt sind, da der installer der demo davon ausgeht dass es beginnend mit id=1 dort in die rex_template tabelle schreiben kann.

Dies funktioniert aber nicht wenn bereits dort datensätze vorm demo setupmenthalten sind (oder schonmal waren, weil der auto increment wert dann hoch geht).

Ich denke eine lösung könnte sein dass die demo mit template-keys statt id arbeitet.
Dadurch würde die rex min version 5.9 oder neuer sein: https://github.com/redaxo/redaxo/issues/910

https://github.com/FriendsOfREDAXO/demo_onepage/blob/0f679dc6fa22bebf98f38bf3d02f2e4557fa8a91/backups/demo_onepage.utf8.sql#L648-L657

**Comment by schuer** [comment]
Heute das Thema nochmal gehabt. Es liegt offenbar am Developer-AddOn, das nach erfolgreicher Installation der Demo beim nächsten Request die alten Inhalte aus dem Filesystem wieder in die Datenbank gibt.

Bugfix (für alle drei Demos) kann ich übernehmen.

**Comment by staabm** [comment]
fixed mit https://github.com/FriendsOfREDAXO/demo_onepage/commit/abd2e25252021c64a7640f5bd81c4d981d1066cc

danke @schuer
