### ISSUE TITLE
Package: REX 5.5.1 benötigt?

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/demo_onepage#5]
https://github.com/FriendsOfREDAXO/demo_onepage/blob/cd2530d1a806ca69cacf962949d6f1c98cf20e3b/package.yml#L15

Wird REDAXO 5.5.1 wirklich technisch benötigt, oder funktionieren auch ältere Versionen? Wenn ja, fände ich sinnvoll, die Version runterzusetzen.

**Comment by polarpixel** [comment]
Es gehen sicher auch ältere versionen. Welche version würdest du vorschlagen?

**Comment by schuer** [comment]
_Eigentlich_ sollte man die älteste Version angeben, die technisch funktioniert. In der Basisdemo ist es REX 5.3 (vermutlich wegen dem Cache-Buster, der vorher manuell im AddOn abgefeiert wurde). Vielleicht wäre die hier auch passend.

**Comment by polarpixel** [comment]
Es gab da doch ein kleines Sicherheitsproblem (muss nachforschen, mit welcher Version das behoben wurde) – ich würde die Mindestversion nennen nach diesem Update, damit ältere Versionen möglichst ausgemerzt werden.

**Comment by tbaddade** [comment]
Ich würde es bei 5.5.1 belassen.

- 5.5.1 kamen einige Securityfixes rein
- 5.5.0 kam der CSRF-Schutz

**Comment by staabm** [comment]
ich sehe es wie @schuer und würde eine ältere version nehmen, z.b. R5.3 - insofern die demo damit funktioniert.

core security ist nicht aufgabe der demo und stattdessn sollte die demo versuchen in möglichst vielen redaxo core versionen installierbar zu sein, um ein möglichst großes Publikum anzusprechen.

**Comment by gharlan** [comment]
Ich gehe da gedanklich etwas anders ran. Ich frage mich, wird wirklich jemand sich R5.3 neu installieren um darin eine Demo auszuprobieren. Meine Vermutung geht da stark in Richtung "Nein".
Und daher ist es aus meiner Sicht unnötige Arbeit die Demo mit älteren Versionen zu testen.
Aber wenn es jemand machen möchte, schadet es natürlich auch nicht, und man kann dann die Version runtersetzen. Wobei man dann halt auch in Zukunft drauf achten muss.
Ich würde da echt pragmatischer denken, und die aktuelle Version nehmen, da ich eben vermute dass gar kein reales Interesse daran besteht, die Demo mit älteren Versionen zum laufen zu bringen.

Was anderes ist es, wenn es die Demo dann nun schonmal gibt, dann würde ich auch schauen, dass man nicht unnötig die Version hochsetzt.

**Comment by schuer** [comment]
Ich bin nur deshalb auf das Thema gekommen, weil ich in meinem lokalen Setup ein R 5.5.0 hatte, als ich die Demo testen wollte. Und da flog halt erstmal eine Meldung. Mich hat es dann natürlich nicht von der Demo abgehalten, aber dennoch fände ich grundsätzlich sinnvoll, die Hürden so gering wie möglich zu halten.

**Comment by gharlan** [comment]
Zu beachten ist zum Beispiel, dass die Struktur der `rex_config`-Tabelle in 5.4 geändert wurde.
Wahrscheinlich funktioniert die neuere Variante (die in dieser Demo auch im Dump drin ist) aber auch in älteren Versionen. Eigentlich hatte die Tabelle dort aber eine andere Struktur.
(Siehe auch https://github.com/FriendsOfREDAXO/demo_base/issues/62)

**Comment by schuer** [comment]
Okay, Gregor, das Update der Tabellenstruktur ist doch ein handfester Grund, mit der Mindestversion nicht tiefer zu gehen, finde ich. Denn selbst wenn es technisch funktionierte, würde es doch etwas Chaos in die Datenbank bringen, aus der u. U. später Fehler entstehen könnten.

Aber meine persönliche Mindestversion wäre für dieses AddOn dann eben besagte 5.4, nicht die aktuelle 5.5.1.

**Comment by AWqxKAWERbXo** [comment]
Sehe gar kein Problem, die Demo auf 5.5.0/5.5.1 zu belassen und so zu unterstreichen, dass die Aktualität einer REDAXO-Installation wichtig und zu gewährleisten ist. Plus das Testaufwand-Argument.

**Comment by polarpixel** [comment]
Ich schließe das hier dann, ok?
Generell würde ich schon so vorgehen, Core und die verwendeten AddOns immer auf die aktuelle Version zu heben. Denn ich glaube schon, dass man die Demo nur bei einer neuen, bzw. leeren Installation einspielen wird, sodass ein rasches Update schnell gemacht.
