### ISSUE TITLE
help.php & update.php entfernen

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/demo_onepage#7]
Wenn die `help.php` nicht vorhanden wäre, würde im REDAXO stattdessen die `README.md` ausgegeben. Damit müssten wir Hilfetexte zukünftig nur noch an einer Stelle pflegen.

Die `update.php` ist leer und könnte zur besseren Übersicht entfernt werden.

**Comment by polarpixel** [comment]
Sollten in der update.php nicht Infos zu den Updates hinterlegt werden, was jeweils ergänzt wurde?
Würdest Du das in der readme abhandeln?

**Comment by schuer** [comment]
Das wäre eine `CHANGELOG.md`. Die aber auch nicht zwingend notwendig ist, wenn man die Infos immer im GitHub-Release hinterlegt. Ich sehe gerade, in der Basisdemo heißt sie `UPDATE.md`. Man könnte überlegen, es einheitlich zu machen, wobei `CHANGELOG.md` bei GitHub Best-Practice ist.

**Comment by schuer** [comment]
Achso ja, und auf deine Frage hin: Unten in die `README.md` hinein könnte man das Changelog natürlich auch stecken. Ist alles möglich.

(Ich persönlich habe es bisher immer in den GitHub-Releases gepflegt, weil man es dort eh machen sollte und ich zu faul war, es zusätzlich noch in einer Datei zu hinterlegen. Siehe etwa https://github.com/FriendsOfREDAXO/cache_warmup/releases)

**Comment by gharlan** [comment]
Ich bin für `CHANGELOG.md`.
Überlege auch, die irgendwann so wie die `README.md` automatisch in REDAXO einzulesen.

**Comment by schuer** [comment]
Das wäre cool, ja. Unter der Prämisse unbedingt `CHANGELOG.md`, weil das quasi alle so machen.

**Comment by polarpixel** [comment]
Habe ich entsprechend geändert.
